import { describe, expect, it } from 'vitest';
import {
  PROTOCOL_VERSION,
  isTelemetrySnapshot,
  type TelemetrySnapshot,
} from '@apexhud/protocol';

const snapshot: TelemetrySnapshot = {
  protocolVersion: PROTOCOL_VERSION,
  sequence: 42,
  timestamp: '2026-07-25T12:00:00.000Z',
  source: 'mock',
  connection: {
    connected: true,
    status: 'Test',
    tickRate: 60,
    framesDropped: 0,
    simulatorWindow: {
      processRunning: true,
      windowFound: true,
      isVisible: true,
      isMinimized: false,
      isForeground: true,
    },
  },
  session: {
    sessionNumber: 0,
    state: 4,
    sessionType: 'Race',
    sessionName: 'Race',
    eventType: 'Race',
    trackName: 'Test Track',
    trackLengthMeters: 5000,
    sessionTimeSeconds: 120,
    timeOfDaySeconds: 43200,
    timeRemainingSeconds: 1800,
    hasTimeLimit: true,
    lapsRemaining: 0,
    hasLapLimit: false,
    flags: 0,
    isReplayPlaying: false,
    isInGarage: false,
  },
  player: {
    carIndex: 1,
    name: 'Driver',
    carNumber: '32',
    teamName: 'ApexHUD',
    carClassId: 101,
    carClassName: 'GT3',
    iRating: 2500,
    license: 'A 3.50',
    position: 2,
    classPosition: 2,
    lap: 4,
    lapDistancePercent: 0.5,
    speedMetersPerSecond: 60,
    fuelLiters: 40,
    lastLapSeconds: 90,
    bestLapSeconds: 89.5,
    incidentCount: 0,
    onPitRoad: false,
    isOnTrack: true,
  },
  vehicle: {
    speedMetersPerSecond: 60,
    gear: 4,
    rpm: 6500,
    shiftLightFirstRpm: 5500,
    shiftRpm: 6800,
    shiftLightLastRpm: 7000,
    shiftLightBlinkRpm: 7200,
    throttle: 0.8,
    throttleRaw: 0.82,
    brake: 0,
    brakeRaw: 0,
    clutch: 0,
    handbrake: 0,
    handbrakeRaw: 0,
    steeringWheelAngleRadians: 0.1,
    steeringWheelAngleMaxRadians: 7.85,
    shiftIndicatorPercent: 0.74,
    shiftPowerPercent: 0.6,
    onPitRoad: false,
    trackSurface: 3,
    trackSurfaceMaterial: 2,
  },
  driverAids: {
    absAvailable: true,
    absActive: true,
    absCutPercent: 0.35,
    tractionControlAvailable: true,
    tractionControlEnabled: true,
    tractionControlLevel: 5,
    tractionControlLevel2: 2,
    brakeBiasAvailable: true,
    brakeBiasPercent: 53.4,
    pitLimiterAvailable: true,
    pitLimiterActive: false,
    revLimiterActive: false,
    engineWarningsAvailable: true,
    engineWarnings: 0,
    waterTemperatureWarning: false,
    fuelPressureWarning: false,
    oilPressureWarning: false,
    oilTemperatureWarning: false,
    engineStalled: false,
  },
  pit: {
    dataAvailable: true,
    pitsOpen: true,
    inPitStall: false,
    pitstopActive: false,
  },
  environment: {
    dataAvailable: true,
    airTemperatureCelsius: 22,
    trackTemperatureCelsius: 31,
    trackWetness: 0,
    weatherDeclaredWet: false,
  },
  motion: {
    dataAvailable: true,
    lateralAccelerationMetersPerSecondSquared: 4.2,
    longitudinalAccelerationMetersPerSecondSquared: -1.5,
  },
  timing: {
    currentLap: 4,
    completedLaps: 3,
    currentLapSeconds: 45,
    lastLapSeconds: 90,
    bestLapSeconds: 89.5,
    deltaToBestSeconds: -0.12,
    deltaAvailable: true,
    deltaToOptimalLapSeconds: 0.2,
    deltaToOptimalLapAvailable: true,
    deltaToSessionBestLapSeconds: 0.7,
    deltaToSessionBestLapAvailable: true,
    deltaToSessionOptimalLapSeconds: 0.9,
    deltaToSessionOptimalLapAvailable: true,
    deltaToLastLapSeconds: -0.1,
    deltaToLastLapAvailable: true,
    currentLapValid: true,
    validity: 'valid',
  },
  fuel: {
    levelLiters: 40,
    usePerHourLiters: 100,
    estimatedPerLapLiters: 2.5,
    estimatedLapsRemaining: 16,
    requiredToFinishLiters: 35,
    addToFinishLiters: 0,
    samples: 5,
    estimateReady: true,
  },
  radar: { spotterState: 'clear', active: false, contacts: [] },
  relative: { entries: [] },
  standings: { mode: 'overall', entries: [] },
};

describe('telemetry protocol v6', () => {
  it('accepts a complete v6 snapshot with ABS and expanded scopes', () => {
    expect(PROTOCOL_VERSION).toBe(6);
    expect(isTelemetrySnapshot(snapshot)).toBe(true);
  });

  it('rejects a snapshot missing the required driver-aids scope', () => {
    const invalid = structuredClone(snapshot) as unknown as Record<string, unknown>;
    delete invalid.driverAids;
    expect(isTelemetrySnapshot(invalid)).toBe(false);
  });
});
